security:

    providers:
        in_memory:
            memory: ~

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: public.home.index
                use_referer: true
                success_handler: redirect.after.login
            logout:
                target: public.home.index
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/professeur, role: ROLE_TEACHER }
        - { path: ^/eleve, role: ROLE_STUDENT }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_TEACHER,ROLE_STUDENT]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
            FOS\UserBundle\Model\UserInterface: sha512