# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    public.commentaire.type.class: PublicBundle\Form\CommentaireType
    public.commentaire.model.class: PublicBundle\Entity\Commentaire

services:
    redirect.after.login:
        class: UserBundle\Service\AfterLoginRedirection
        arguments: [@router]

    manageMultiple : 
        class: DashboardBundle\Service\ManageMultiple
        arguments: [@doctrine]