<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Util\Debug as Debug;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getThreeLastPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.createAt','DESC')
            ->where('p.status = 1')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function getPostByPage($page){
        $nbParPage = 2;
        $offset = $page * $nbParPage - 1 ;
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.createAt','DESC')
            ->where('p.status = 1')
            ->setFirstResult($offset)
            ->setMaxResults($nbParPage)
            ->getQuery()
            ->getResult();
        return $results;
    }

    public function getPostTitle($max){
        $results = $this
            ->createQueryBuilder('p')
            ->orderBy('p.createAt','DESC')
            ->where('p.status = 1')
            ->setFirstResult(4)
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();

        return $results;
    }
}
