<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getThreeLastPost(){
        $results = $this
            ->createQueryBuilder('p')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $results;
    }
}
