<?php

namespace DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixRepository extends EntityRepository
{
}
