<?php

namespace DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
    public function getFichesById(Array $ids){
        $stringIds = implode(' ,',$ids);
        $results = $this
            ->createQueryBuilder('f')
            ->where ('f.id IN (' . $stringIds . ')')
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function getFichesByTeacher($id, $page, $itemsPerPage) {
        $offset = ($page - 1) * $itemsPerPage;
        $results = $this
            ->createQueryBuilder('f')
            ->join('f.teacher','t')
            ->where('f.teacher = :id')
            ->setParameter(':id',$id)
            ->setFirstResult($offset)
            ->setMaxResults($itemsPerPage)
            ->getQuery()
            ->getResult();

        return $results ;
    }

    public function getTotalFichesByTeacher($id, $itemsPerPage) {
        $totalFiches = $this
            ->createQueryBuilder('f')
            ->join('f.teacher','t')
            ->select('COUNT(f.id) AS total')
            ->where('f.teacher = :id')
            ->setParameter(':id',$id)
            ->getQuery()
            ->getSingleScalarResult();

        $totalFichesPages = ceil($totalFiches / $itemsPerPage);
        return $totalFichesPages;
    }

}
