<?php

namespace DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends EntityRepository
{
    public function getFichesById(Array $ids){
        $stringIds = implode(' ,',$ids);
        $results = $this
            ->createQueryBuilder('f')
            ->where ('f.id IN (' . $stringIds . ')')
            ->getQuery()
            ->getResult();

        return $results ;
    }
}
